### ISSUE TITLE
Plans for releasing the codes?

### ISSUE THREAD

**Issue by guanhuaw** [mrirecon/spreco#1]
Hi,
It is really enjoyable to read the pre-print on MCMC-based reconstruction. And I was wondering if there are some timelines for releasing the code for reproducibility? Thanks!

**Comment by ggluo** [comment]
> Hi, It is really enjoyable to read the pre-print on MCMC-based reconstruction. And I was wondering if there are some timelines for releasing the code for reproducibility? Thanks!

Hi, thanks for your interest. This repository was updated. Feel free to try it and looking forward to some feedbacks.
