### ISSUE TITLE
NAN in the training 

### ISSUE THREAD

**Issue by Yue91** [mrirecon/spreco#13]
Hi, 

Very good work! I'm very interested in reproducing it. 

Do you encounter NAN during the training? I have check the input data which doesn't include the NAN. 

 Tfdbg says the NAN comes from Conv2D. I reduce the learning rate to 1e-8, but the NAN still exits.
![Uploading tfdbg.png…]()

Can you help me?

 Thank you!

**Comment by ggluo** [comment]
Hi, 

could you provide more details?

**Comment by Yue91** [comment]
Thanks, this issue has been solved. 

I inadvertently utilized the incorrect code version—the default main branch. 
The version labeled as "mrm_paper" didn't have this issue.
